version: '3'
services:
  nginx:
    image: nginx:1.14-alpine
    ports:
    - 80:80
    volumes:
    - ./:/app
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/nginx/mime.type:/etc/nginx/mime.type
    - ./docker/nginx/conf.d/vhost.conf:/etc/nginx/conf.d/vhost.conf
#    - ./nginx/vhost.conf:/etc/nginx/vhost.conf
    depends_on:
    - php
  php:
    build: docker/php
    volumes:
    - ./:/app
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  mysqldb:
    image: mysql:5.7
    volumes:
      - ./_db:/var/lib/mysql
#      - ./docker/mysql/config.cnf:/etc/mysql/my.cnf
#      - ./docker/mysql/dump/:/home/
#      - ./docker/mysql/sql_import:/etc/mysql/sql_import
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sol
      MYSQL_USER: maks
      MYSQL_PASSWORD: maks
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.5
    environment:
#    - PMA_ARBITRARY=4
    - PMA_VERBOSE=sol
    - PMA_PORT=3306
    - PMA_USER=root
    - PMA_PASSWORD=root
    - PMA_HOST=mysqldb
    links:
      - mysqldb:db
    depends_on:
      - mysqldb
    #restart: always
    ports:
    - 8099:80
    volumes:
    - /sessions